- graphiql-spring-boot-autoconfigure/src/main/resources/META-INF/resources/index.html
This is a fix for character encoding issue in some browser, e.g. FireFox reports on missing encoding meta tag:
> The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
Plus we align with other meta tags currently set in `express-graphql`, see https://github.com/graphql/express-graphql/commit/775914b5689cfc781c99cf705292e1dcffd2239a
> GraphiQL: meta tags

- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/GraphiQLController.java
The annotation attribute `produces` is ignored when writing directly on the `OutputStream` of the `response`. I've removed that and now explicitly set the `Content-Type` header before writing to the `OutputStream`, thereby ensuring that the browser understands the response. In my case Google Chrome was showing it as plain text instead of html.
> Added Content-Type header to GraphiQL response

- graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.java
it took me very long to find out that you have to configure jackson in 2 different places - this avoids it.
Additionally, I was thinking about using JacksonAutoConfiguration - is this a good idea?
> reuse jackson configuration for schema parser

- README.md
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/GraphiQLController.java
- graphiql-spring-boot-autoconfigure/src/main/resources/graphiql.html
A small pull request that adds a simple feature: the ability to change the GraphiQL page title using a Spring Boot parameter (through the standard `application.yml` file or any other mean of setting Spring Boot parameters).
Here is my motivation for this pull request: I'm currently working on a quite big project which has many microservices. Each one of these microservices exposes its own GraphiQL page. I (and my colleagues) end up with many tabs in the browser all having exactly the same name... and it's sometimes a bit difficult to find the one I'm actually interested in! ^^
(P.S. Thank you for this cool project!)
> Add configuration parameter to change the GraphiQL page title

- voyager-spring-boot-autoconfigure/src/main/resources/voyager.html
Hi,
on my machine it looked like the graph area from voyager was kind of cut of as soon as I start zooming or navigating through the graph diagram. It looked like the display area has only the initial size from the graph.
I added some styles based on the setup of the voyager project itself
> Some styling to prevent voyager graph cut off

- example-graphql-tools/build.gradle
- example-graphql-tools/src/main/java/com/embedler/moon/graphql/boot/resolvers/Mutation.java
- example-graphql-tools/src/main/java/com/embedler/moon/graphql/boot/resolvers/Post.java
- example-graphql-tools/src/main/resources/graphql-tools.graphqls
- example-graphql-tools/src/test/java/com/embedler/moon/graphql/boot/GraphQLToolsSampleApplicationTest.java
- example-graphql-tools/src/test/resources/graphql/create-post.graphql
- example-graphql-tools/src/test/resources/graphql/query-wrapper.json
- graphql-spring-boot-starter-test/build.gradle
- graphql-spring-boot-starter-test/src/main/java/com/embedler/moon/graphql/testing/GraphQLTestUtils.java
- graphql-spring-boot-starter-test/src/main/java/com/embedler/moon/graphql/testing/TestingConfiguration.java
- graphql-spring-boot-starter-test/src/main/resources/META-INF/spring.factories
- Move GraphQLTestUtils to graphiql-spring-boot-starter project
- Use ObjectMapper to create test requests
- Enable auto configuration
- Add mutation show case
> Add graphiql-spring-boot-starter project

- README.md
- example-graphql-tools/src/main/resources/application.yml
- example-graphql-tools/src/main/resources/defaultQuery.graphql
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/GraphiQLController.java
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/PropertyGroupReader.java
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/PropsLoader.java
- graphiql-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
- graphiql-spring-boot-autoconfigure/src/main/resources/graphiql.html
This PR adds a couple of requested features:
* Ability to configure props for GraphiQL through Spring properties, e.g. `defaultQuery`, `query`, etc. See the updated README for details.
* Ability to configure headers to be sent when using GraphiQL, e.g. `graphiql.headers.Authorization`.
Working examples of both use cases can be seen in the **example-graphql-tools** sample app.
@elenigen @aSemy @marceloverdijk Please review
> GraphiQL improvements

- README.md
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/GraphiQLController.java
- graphiql-spring-boot-autoconfigure/src/main/resources/graphiql.html
Fixes #117 
Added GraphiQL configurations for subscriptions endpoint and static content.
The proposed implementation requires a configuration of that type:
```yml
graphiql:
endpoint:
graphql: /graphql
subscriptions: /subscriptions
static:
basePath: /
```
> Graphiql endpoints configuration

- graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.java
If the default object mapper is being used, prefer the one that has been provided by Spring Boot
> Fix #134 by auto configuring after Jackson

- graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLServletProperties.java
- graphql-spring-boot-autoconfigure/src/test/java/com/oembedler/moon/graphql/boot/test/GraphQLServletPropertiesTest.java
Setter was missing in `GraphQLServletProperties` (fix #148)
> Added missing setter async mode

- example-graphql-tools/src/test/java/com/oembedler/moon/graphql/boot/GraphQLToolsSampleApplicationTest.java
- example-graphql-tools/src/test/java/com/oembedler/moon/graphql/boot/SpringBootTestWithoutWebEnvironmentTest.java
- graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLWebsocketAutoConfiguration.java
Reverted conditional back to `@ConditionalOnClass` again. This leads to the requirement that unit tests using `@SpringBootTest` need to be started with a `webEnvironment` because otherwise they won't start at all complaining about a missing `ServerContainer` (fixes #150).
> Revert conditional on ServerEndpointExporter

- graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.java
Fixed `BeanNoSuchBeanDefinitionException` thrown by `GraphQLWebAutoConfiguration.graphQLObjectMapper` when `graphql.servlet.use-default-objectmapper` is set to `false` and no bean for `ObjectMapperProvider` is provided by an application.
This also allows users to specify an `ObjectMapperConfigurer` bean. Currently, it will never be used because a `ObjectMapperProvider` bean is essentially required to always exist.
> Fixed BeanNoSuchBeanDefinitionException caused by use-default-objectmapper=false & fixed ability to use ObjectMapperConfigurer

- graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLInstrumentationAutoConfiguration.java
- graphql-spring-boot-autoconfigure/src/test/java/com/oembedler/moon/graphql/boot/test/instrumentation/GraphQLInstrumentationAutoConfigurationTest.java
Before this fix TracingNoResolversInstrumentation is only provided if tracing-enabled is explicitly
set to false. Even if actuator-metric is set to to true, metrics wont be available because
metricsInstrumentation requires a TracingInstrumentation bean.
> fix(): actuator-metrics works without explicitly setting tracing-enabled to false

- README.md
They are not necessary at compile time.
> Import web UI modules with scope 'runtime'

- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java
This PR https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/176 introduced a bug where the global `Content-Type` header for multipart requests was forced to `application/json;charset=UTF-8` instead of `multipart/form-data`. This makes the query parser fail.
This fixes #216
> Don't reuse global headers for JSON parts

- graphql-spring-boot-test-autoconfigure/src/main/java/com/graphql/spring/boot/test/GraphQLTest.java
With default filters enabled, include filters are applied in addition to the
default filters (`@Component`, ...).
> fix(): disable component scan default filters in GraphQLTest

- graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.java
- graphql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphql/boot/GraphQLToolsProperties.java
I've made some changes to allow SchemaParserOptions to be configured via properties.
Main motivation is so that you can set `allowUnimplementedResolvers=true` for tests. 
If you'd like me to change anything else please let me know,
> Enable all schema parser options to be set via properties

- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLResponse.java
Currently there is no simple way to get a type-safe list from `GraphQLResponse`. `get("$.data.fooBars", List.class)` would return a list of `LinkedHashMap`s, requiring an additional step to convert these to a list of POJOs.
This small new method is intended to simplify this repetitive step.
> feat: added method to type-safely get List of objects

- example-graphql-tools/src/test/java/com/graphql/sample/boot/GraphQLToolsSampleApplicationTest.java
- example-graphql-tools/src/test/resources/graphql/all-comment-fields-fragment.graphql
- example-graphql-tools/src/test/resources/graphql/post-get-comments-with-fragment.graphql
- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLTestTemplate.java
This PR is to meet a need discovered recently while writing tens of tests using the same return types, and discovering that the `GraphQLTestTemplate` doesn't support querying with fragments (or at least not obviously):
For example, given the following graphqls query resource files:
- `some-fragment.graphqls`
- `some-query-using-fragment.graphqls`
`graphQLTestTemplate.postForResource('graphql/some-query-using-fragment.graphqls')` will fail.
This PR adds overloaded methods to `GraphQLTestTemplate#postForResource` and `GraphQLTestTemplate#perform`, so that the above scenario can be handled with:
```
graphQLTestTemplate.postForResource(
'graphql/some-query-using-fragment.graphqls', 
List.of(some-fragment.graphqls)
)
```
And can be applied to an arbitrary number of fragments.
> add support for testing with graphql fragments

- graphql-kickstart-spring-support/src/main/java/graphql/kickstart/spring/AbstractGraphQLController.java
Hi I'm glad to find best graphql library for java.
I think in AbstratGraphQLController "if statement" is bad for readability in such simple condition.
It is better to use ternary operator.
> refactor if statement

- README.md
Current verison refers to 6.0.0 that has the content length issue.
> docs: update version in readme

- graphiql-spring-boot-autoconfigure/build.gradle
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/GraphiQLAutoConfiguration.java
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/GraphiQLController.java
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/ReactiveGraphiQLController.java
- graphiql-spring-boot-autoconfigure/src/main/java/com/oembedler/moon/graphiql/boot/ServletGraphiQLController.java
- graphiql-spring-boot-autoconfigure/src/test/java/com/oembedler/moon/graphiql/boot/ReactiveGraphiQLControllerTest.java
- graphiql-spring-boot-autoconfigure/src/test/java/com/oembedler/moon/graphiql/boot/ServletGraphiQLControllerTest.java
Basically, I need GraphiQL when using Webflux and not MVC. Therefore, I tried to reuse as much code as possible and abstract away the specifics. I'm not completely sure how to test the two versions (servlet and reactive) separately. I was hoping somebody here might have an idea.
> Add support for GraphiQL in a reactive context

- graphql-spring-boot-test/build.gradle
- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLResponse.java
- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLTestTemplate.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLResponseTest.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/TestApplication.java
GraphQLResponse and GraphQLTestTemplate now use the ObjectMapper bean
from the tested application.
The `get` methods now use the object mapper to convert the variable to
the specified type. Formerly they used vanilla JsonPath library methods
that may produce unexpected results. E. g. given the following response
body:
`{"data": {"test": 2}}`
a call to `get("$.data.test")` would result in an
`ClassCastException`, which is usually not the desired behaviour.
It was also very restrictive on data types: only "native" JSON types
were supported (e. g. int, boolean, String).
Furthermore it seems to have issues with more complex classes, like
POJOs and may return `null`.
Several test cases were added to ensure correct behaviour. Some of
these tests would fail with the previous version.
> feat: improvements for GraphQL response testing facilities

- playground-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json
This property was missing from additional spring configuration
metadata.
> fix: add missing auto-complete support for graphql.playground.enabled

- voyager-spring-boot-autoconfigure/src/main/resources/META-INF/spring.factories
link https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/374
`org.springframework.boot.autoconfigure.EnableAutoConfiguration` in `spring.factories` is **Duplicate property key** and could not be work.
> fix Duplicate EnableAutoConfiguration Key

- README.md
`subscriptionsEndpoint` was incorrect and would not work
> docs(#429): fix typo in Playground documentation

- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLTestSubscription.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLTestSubscriptionTestBase.java
Also includes some minor fixes and improvements to
GraphQLTestSubscription behaviour.
Apparently, there were several potential causes of failure on the
pipeline:
- the web socket connection was not properly closed after certain tests
(reset was not called after tests)
- web socked connection timed out (solved by increasing connection
timeout)
- value of "acknowledged" could be true after reset (init method now
waits for the "acknowledged" message to arrive)
- "responses" may not be empty after reset (solved by making clear call
synchronized)
> fix: GraphQLTestSubscription test failing

- graphql-kickstart-spring-webflux/src/main/java/graphql/kickstart/spring/webflux/GraphQLController.java
Prior to this PR, the Webflux version of graphql-spring-boot did not use GraphQLObjectMapper to map the execution result. This meant that the error messages could not be customized by creating a custom GraphQLErrorHandler.
> Update GraphQLController to use ObjectMapper to map ExecutionResult

- build.gradle
ignoredSnapshotDependencies had spelling issues
> artifact name spelling fix in build.gradle

- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/ReactiveVoyagerController.java
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/VoyagerController.java
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/VoyagerIndexHtmlTemplate.java
Hello! I added url templating for graphQL endpoint as in graphiql controller.
> Add graphQL endpoint template resolve as in graphiql controller.

- graphql-kickstart-spring-webflux/src/main/java/graphql/kickstart/spring/webflux/GraphQLSpringWebSocketSessionContext.java
made GraphQLSpringServerWebExchangeContext public rather than internal so that it can be referenced by dependent projects
fixes #426
> [fixes #426] made GraphQLSpringServerWebExchangeContext public 

- graphiql-spring-boot-autoconfigure/src/main/resources/graphiql.html
Although the headers editor was present (#441), it was non-functional because only the preconfigured headers were submitted, regardless of the content of the request headers tab.
> fix(graphiql): request headers not submitted with the request

- .github/workflows/ci.yml
By setting BINTRAY_USER to SKIP_BINTRAY_PUBLISH, it is possible now to disable the snapshot publishing job, allowing master branches of forks to successfully pass the ci.
> ci: allow successful build on master branches of forks

- README.md
I spent a few hours trying to figure out how to get CORS working properly.  Issue [498](https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/498) had the solution.  I think these options should be added to the main README.
> choir: update README.md with required CORS properties

- README.md
This starter was missing in the readme.md
> Adding details on how to add GraphQL Playground starter

- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLTestSubscription.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLSubscriptionTestAwaitNoAnswerTest.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLTestSubscriptionAwaitAndGetResponseTest.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLTestSubscriptionTestBase.java
If `numExpectedResponses `was 0 or negative, the method did not work according to documentation, it did not wait out the specified amount of time as the condition in await() was fulfilled immediately.
This resulted in `waitAndExpectNoResponse` and  `awaitAndGetAllResponses` not working as specified in the documentation.
The test suite was also updated to catch this issue in the future.
> fix: test subscription not waiting the specified amount of time

- graphql-kickstart-spring-support/src/main/java/graphql/kickstart/spring/error/GraphQLErrorFromExceptionHandler.java
- graphql-kickstart-spring-support/src/test/java/graphql/kickstart/spring/error/GraphQLErrorFromExceptionHandlerTest.java
The methods on GraphqlErrorBuilder each contain [an assertion that the supplied data is non-null](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/GraphqlErrorBuilder.java#L77), but it is not required that these elements be non-null on every throw GraphQLError. For example, errors often omit a `path` property, which will lead to an unhandled `graphql.AssertException` when the error is handled by `GraphQLErrorFromExceptionHandler.java`. 
At present, type coercion errors always result in a HTTP response with an empty body and a 400 response code due to the way graphql-java [normalizes `CoercingParseValueException`s](https://github.com/graphql-java/graphql-java/blob/v16.2/src/main/java/graphql/execution/ValuesResolver.java#L173)
> Only call GraphqlErrorBuilder with non-null data

- renovate.json
Manually configure `graphql-spring-boot` because its based off a fork
> Setting renovate config file to run on forks

- .github/workflows/ci.yml
Sonar check will no longer run if SONAR_TOKEN is not provided. Also, Bintray publish will also be skipped if BINTRAY_USER  is null (formerly it was only skipped if explicitly set to SKIP_BINTRAY_PUBLISH in the secrets of the forked repository).
> Allow successful CI workflow runs on master branch of forks

- README.md
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/ReactiveVoyagerAutoConfiguration.java
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/ReactiveVoyagerController.java
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/VoyagerAutoConfiguration.java
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/VoyagerIndexHtmlTemplate.java
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/VoyagerPropertiesConfiguration.java
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/properties/VoyagerCdn.java
- voyager-spring-boot-autoconfigure/src/main/java/graphql/kickstart/voyager/boot/properties/VoyagerDisplayOptions.java
- voyager-spring-boot-autoconfigure/src/main/resources/voyager.html
- Standardizing basePath to match playground and altair tools
- Support all of the common Voyager configuration options via properties
- Adding README entry to document Voyager and the configuration options available
> Voyager configuration options

- .github/workflows/pull-request.yml
- .gitignore
- CONTRIBUTING.md
- commitlint/commitlint.config.js
- commitlint/package-lock.json
- commitlint/package.json
This PR proposes to use Conventional Commits on the project from now on and enforce this via the CI.
Commit messages are validated by the CI for each pull request,  and aslo adds an  easy way to set up a git hook for local development (to catch violations before comitting).
Also adds separated contributing guideline file. Moved there the Contributions section from the readme, as well as added a section about commit messages / commitlint. 
Note:
- Bots may need to be configured to commit according to the specs (but as I see renovate already does that).
- The "from" commit may also need to be changed depending on the time of merging.
Question / Potential improvements:
- Is it possible to dynamically check only new commits added by the actual PR?
> Add commitlint - use conventional commits consistently

- CONTRIBUTING.md
Fixes the problem that "Commit messages" is displayed as "###Commit messages"
https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/master/CONTRIBUTING.md
> docs: displayed as "###Commit messages"

- graphql-spring-boot-dependencies/build.gradle
Two files were generated, an empty` mavenJava/pom-default.xml` and a `mainProjectPublication/pom-default.xml` with proper content.
The published artifact used th empty from `mavenJava`.
This update fixes the issue by adding proper content to mavenJava.
> fix(dependencies): generate and publish proper pom file

- build.gradle
"enabled" is replaced by "required"
> chore: update deprecated properties in jacoco test reports

- graphql-kickstart-spring-webflux/src/main/java/graphql/kickstart/spring/webflux/ReactiveWebSocketSubscriptionSession.java
Hi !
This PR should fix a memory leak when using webflux with subscriptions and KeepAlive.
**ApolloSubscriptionKeepAliveRunner** is responsible for sending keep alive messages through the websocket as long as the websocketSubscriptionSession is "opened". This runner, uses a scheduled Executor for this purpose.  
When a subscription is closed, of an exception occurs while sending message, KeepAlive message is not more scheduled and everything works fine.
**Bug** :
ReactiveWebSocketSubscriptionSession is the object representing a Reactive Subscription, this object always return `true`on the `isOpen`method, the keepAliveRunner will never stop sending messages, and stack references to dead subscriptions (Memory leak).  
No exception occurs while sending messages on a closed subscription, …
> fix: Memory leak when using reactive subscriptions with KeepAlive

- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/editor/graphiql/GraphiQLController.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/editor/graphiql/GraphiQLProperties.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/AsyncServletProperties.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/GraphQLServletProperties.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/GraphQLWebAutoConfiguration.java
- graphql-spring-boot-autoconfigure/src/test/java/graphql/kickstart/autoconfigure/annotations/GraphQLAnnotationsSubscriptionTest.java
- graphql-spring-boot-test-autoconfigure/src/test/java/com/graphql/spring/boot/test/GraphQLTestAutoConfigurationTestBase.java
- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLTestSubscription.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLTestSubscriptionGetRemainingResponsesTest.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLTestSubscriptionTestBase.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLTestSubscriptionUsageErrorHandlingTest.java
fixes #645 move milliseconds and seconds to duration
> Move milliseconds and seconds to duration

- graphql-kickstart-spring-support/src/main/java/graphql/kickstart/spring/AbstractGraphQLController.java
- graphql-kickstart-spring-webflux/src/main/java/graphql/kickstart/spring/webflux/GraphQLController.java
(reopening of https://github.com/graphql-java-kickstart/graphql-spring-boot/pull/653)
Hi, I've opened a pull request in https://github.com/graphql-java-kickstart/graphql-java-servlet as well, this fix depends on it. This pull request should fix the following issue:
When using Apollo persisted queries via angular-apollo I get the following error in browser console:
`Invalid Syntax : offending token '<EOF>'`
And the following in server console:
`notprivacysafe.graphql.GraphQL           : Query failed to parse : ''`
Minimal reproduction: https://github.com/ObeyYourMaster/graphql-kickstart-spring-boot-apq-not-working-showcase
My angular setup:
package.json
```javascript
{
"@apollo/client": "3.3.20",
"crypto-es": "1.2.7",
"apollo-angular": "2.6.0"
}
```
ApolloClient setup:
```typescript
export …
```
> fix: 'Invalid Syntax : offending token '<EOF>'' when using Apollo persisted queries

- .github/workflows/ci.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
Eclipse Temurin is the successor of AdoptOpenJDK.
> ci: update java 16 to 17 for PR test run, change distribution to temurin

- graphql-kickstart-spring-support/src/main/java/graphql/kickstart/spring/error/GraphQLErrorHandlerFactory.java
- graphql-kickstart-spring-support/src/test/java/graphql/kickstart/spring/error/GraphQLErrorHandlerFactoryTest.java
While scanning in search of GraphQL error handlers, `GraphQLErrorHandlerFactory` takes into consideration the original method if the bean it's working on is a Spring CGLIB proxy.
In this way, methods annotated with `@ExceptionHandler` are detected as GraphQL error handlers even if the containing bean is wrapped inside a Spring AOP proxy.
> fix(#736): make exception handlers work with Spring proxies

- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLTestTemplate.java
- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/RequestFactory.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/GraphQLTestTemplateIntegrationTest.java
- graphql-spring-boot-test/src/test/java/com/graphql/spring/boot/test/beans/DummyMutation.java
- graphql-spring-boot-test/src/test/resources/test-schema.graphqls
- graphql-spring-boot-test/src/test/resources/upload-file.graphql
- graphql-spring-boot-test/src/test/resources/upload-files.graphql
Came across GraphQL file upload functionality and recognised the `GraphQLTestTemplate` is missing function to handle multi-part file upload for IntegrationTest scenarios. 
The current multipart post function for `GraphQLTestTemplate` is not handling file upload case using built-in [Apollo Upload scalar](https://github.com/graphql-java-kickstart/graphql-java-servlet/blob/eb4dfdb5c0198adc1b4d4466c3b4ea4a77def5d1/graphql-java-servlet/src/main/java/graphql/kickstart/servlet/apollo/ApolloScalars.java) from GraphQL Servlet.
Please note that we can't embed binary data into json. Clients library supporting GraphQL file upload will set `variable.files` to `null` for every element inside the array to make it conformed with json blob spec for `operations` part. However, each file will be a part of …
> Function for GraphQLTestTemplate to upload files using Upload scalar

- graphql-spring-boot-test/src/main/java/com/graphql/spring/boot/test/GraphQLTestTemplate.java
This caused Sonar analysis and Publish task failure
> fix: prevent "bad use of '>'" error when generating javadoc

- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/editor/graphiql/GraphiQLAutoConfiguration.java
- graphql-spring-boot-autoconfigure/src/test/java/graphql/kickstart/autoconfigure/editor/graphiql/GraphiQLEnabledTest.java
- graphql-spring-boot-autoconfigure/src/test/java/graphql/kickstart/autoconfigure/editor/graphiql/ReactiveGraphiQLEnabledTest.java
GraphiQL screen works fine with CDN enabled option but when we try to use hosted version we need to define resources manually. voyager reactive configuration already uses automatic static resource loading.
```java
@ConditionalOnProperty(value = "graphql.graphiql.cdn.enabled", havingValue = "false")
```
did not work properly, that's why I put a if condition there.
> Graphiql static resource loading fix

- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/editor/altair/AltairController.java
Since version 4.2.0 jsdelivr is not publishing packages with es-2018 suffix
https://www.jsdelivr.com/package/npm/altair-static?path=build%2Fdist
this change would allow me to use altair 4.6.4
> fix(altair): Made possible to use newer versions of altair over cdn

- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/tools/ClasspathResourceSchemaStringProvider.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/tools/GraphQLJavaToolsAutoConfiguration.java
Hello,
I have tried to use native SB3 builds and faced NPE problem. It's related to graalvm nature of compile time boot.
The following changes helped me to solve it, please take a look
Thank you
> ClasspathResourceSchemaStringProvider to use full constructor instead of field injection

- .github/workflows/pull-request.yml
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/DefaultWsCsrfToken.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/GraphQLSubscriptionWebsocketProperties.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/GraphQLWebsocketAutoConfiguration.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/GraphQLWsServerEndpointRegistration.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/WsCsrfFilter.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/WsCsrfToken.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/WsCsrfTokenRepository.java
- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/WsSessionCsrfTokenRepository.java
- graphql-spring-boot-autoconfigure/src/test/java/graphql/kickstart/autoconfigure/web/servlet/GraphQLWsServerEndpointRegistrationTest.java
- graphql-spring-boot-autoconfigure/src/test/java/graphql/kickstart/autoconfigure/web/servlet/WsCsrfFilterTest.java
- graphql-spring-boot-autoconfigure/src/test/java/graphql/kickstart/autoconfigure/web/servlet/WsSessionCsrfTokenRepositoryTest.java
- graphql-spring-boot-test/build.gradle
> feat: add support for csrf check on websocket upgrade

- graphql-spring-boot-autoconfigure/src/main/java/graphql/kickstart/autoconfigure/web/servlet/metrics/MetricsInstrumentation.java
I updated MetricsInstrumentation such that the correct instrumentExecutionResult method is now overridden. fixes #950
> fix: updated MetricsInstrumentation to implement correct instrumentExecutionResult method
